name: my-cml-attempt
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup_Python
      - uses: actions/setup-python@v2
      - name: Setup_CML
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python data_expl.py
          python nn_train.py
          python nn_train_eval.py
          cat metrics.txt >> report.md
          cml-send-comment report.md
          cml-publish output.jpg --md >> report.md